# Generated by Django 3.0 on 2022-04-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(editable=False, max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='shortname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nombre Corto'),
        ),
    ]
