# Generated by Django 3.0 on 2022-04-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_auto_20220402_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
    ]
