# Generated by Django 3.0 on 2022-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20220402_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'habilidad',
                'verbose_name_plural': 'Habilidad',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Persona'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('first_name', 'last_name')},
        ),
    ]
