# Generated by Django 3.0 on 2022-04-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombres Completops'),
        ),
    ]
