# Generated by Django 3.0 on 2022-04-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_empleado_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres Completops'),
        ),
    ]
